version: '3.8'

services:
  db:
    image: "postgres:12"
    container_name: postgres_db1
    env_file:
      - db_keys.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: