# Generated by Django 3.1.5 on 2021-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210104_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='total_dislikes',
            new_name='total_comments_dislikes',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='total_likes',
            new_name='total_comments_likes',
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_posts_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_posts_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_self_comments_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_self_comments_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_self_posts_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_self_posts_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
