# Generated by Django 3.1.5 on 2021-01-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210107_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='total_comments_dislikes',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='total_comments_likes',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='total_self_comments_dislikes',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='total_self_comments_likes',
        ),
    ]
